networks:
  pcparts_network:
    driver: bridge

services:
  pcparts.api:
    container_name: pcparts.api
    image: ${DOCKER_REGISTRY-}pcpartsapi
    build:
      context: .
      dockerfile: PCParts.API/Dockerfile
    depends_on:
      - pcparts.database
    networks:
      - pcparts_network 
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
       - "8080:8080"
       - "8081:8081"

  pcparts.database:
    image: postgres:latest
    container_name: "pcparts.database"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pcparts
      - POSTGRES_USER=postgres
    volumes:
    - ./.containers/api-db:/var/lib/postgresql/data 
    ports:
    - "5432:5432"
    networks:
      - pcparts_network
