name: 'RabbitMq.container'

networks:
  pcparts_network:
    external: true
  

services:
  RabbitMq: 
    image: rabbitmq:3-management
    container_name: RabbitMq
    restart: always
    networks:
      - pcparts_network
    ports:
      - "5672:5672"     
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
    