clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service_name'


    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - regex:
           expression: '.*\[(?P<detected_level>\w+)\]\s*(?P<message>.*)'
      - drop:
          source: detected_level
          expression: '^(?i)(info|debug|trace)$'